#volumes挂载方式：自定义的文件：容器默认读取的文件
version: '3.8'

volumes:
  mysql_data:

networks:
  vue3-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
#      MYSQL_USER: root 不被允许root，应该是普通用户连接
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vue3db
      MYSQL_ROOT_HOST: '%' # 允许远程连接
    ports:
      - "3306:3306"
    volumes:
      #初始化数据库，避免nacos服务因为数据库是空的导致启动失败
      - ./nacos-init-sql.sql:/docker-entrypoint-initdb.d/mysql-schema.sql
      - mysql_data:/var/lib/mysql
    networks:
      - vue3-network
    command: --default-authentication-plugin=mysql_native_password
#    restart: unless-stopped #自动重启

# 使用kRafka
#  zookeeper:
#    image: zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: "yes" #允许匿名登录dock
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - vue3-network

  #Kafka 服务 (KRaft 模式)
  kafka:
    image: bitnami/kafka:latest
    # image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - vue3-network
    environment:
      # Bitnami 特定的 KRaft 配置
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      # 监听器配置 - 使用 Bitnami 的变量名
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.10.34:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # 集群配置
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # 集群 ID
      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
#    restart: unless-stopped


  # 第一个Nacos节点
  nacos8814:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nacos/nacos-server:v2.3.2
    container_name: nacos8814
    ports:
      - "8814:8848"
      - "9814:9848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=cluster
      - NACOS_SERVERS=nacos8814:8848,nacos8836:8848,nacos8853:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=vue3db
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - NACOS_AUTH_ENABLE=true #此处开启后，需要配置server-addr.username=nacos,server-addr.password=nacos，2.4.0版本开始
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    depends_on:
      - mysql
    networks:
      - vue3-network

  nacos8836:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nacos/nacos-server:v2.3.2
    container_name: nacos8836
    ports:
      - "8836:8848"
      - "9836:9848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=cluster
      - NACOS_SERVERS=nacos8814:8848,nacos8836:8848,nacos8853:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=vue3db
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - NACOS_AUTH_ENABLE=true #此处开启后，需要配置server-addr.username=nacos,server-addr.password=nacos，2.4.0版本开始
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    depends_on:
      - mysql
    networks:
      - vue3-network

  nacos8853:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nacos/nacos-server:v2.3.2
    container_name: nacos8853
    ports:
      - "8853:8848"
      - "9853:9848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=cluster
      - NACOS_SERVERS=nacos8814:8848,nacos8836:8848,nacos8853:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=vue3db
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - NACOS_AUTH_ENABLE=true #此处开启后，需要配置server-addr.username=nacos,server-addr.password=nacos，2.4.0版本开始
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    depends_on:
      - mysql
    networks:
      - vue3-network


  # Nginx 负载均衡器
  nginx:
    image: nginx:latest
    container_name: nginx-balance
    ports:
      - "8848:80"
      - "1080:1080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nacos8814
      - nacos8836
      - nacos8853
    networks:
      - vue3-network
#    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - vue3-network