version: '3.8'

volumes:
  mysql_data:

networks:
  vue3-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vue3db
      MYSQL_ROOT_HOST: '%' # 允许远程连接
    ports:
      - "3306:3306"
    volumes: #加载本地目录下的配置文件到容器目标地址下
      - mysql_data:/var/lib/mysql # 挂载 mysql_data 卷到 /var/lib/mysql 实现数据持久化
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 挂载本地 init.sql 文件到容器初始化目录，用于数据库初始化

    networks:
      - vue3-network
    command: -- default-authentication-plugin=mysql_native_password  # 提高兼容性
    restart: unless-stopped #自动重启


  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes" #允许匿名登录
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - vue3-network

  kafka:
    image: bitnami/kafka:latest
   # image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - vue3-network
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS=true #自动创建主题
    restart: unless-stopped
  nacos8841:
    image: nacos/nacos-server:2.1.0
    container_name: nacos-server
    ports:
      - "8841:8841"
    environment:
      MODE: cluster
      NACOS_SERVER_IP: 192.168.10.66
      NACOS_APPLICATION_PORT: 8841
      NACOS_SERVERS: "192.168.10.66:8841 192.168.10.66:8836 192.168.10.66:8853"
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
    volumes:
      - ./nacos-cluster.conf:/home/nacos/conf/nacos-cluster.conf
    depends_on:
      - mysql
    networks:
      - vue3-network
    restart: unless-stopped

  nacos8836:
    image: nacos/nacos-server:2.1.0
    container_name: nacos-server
    ports:
      - "8836:8836"
    environment:
      MODE: cluster
      NACOS_SERVER_IP: 192.168.10.66
      NACOS_APPLICATION_PORT: 8836
      NACOS_SERVERS: "192.168.10.66:8841 192.168.10.66:8836 192.168.10.66:8853"
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
    volumes:
      - ./nacos-cluster.conf:/home/nacos/conf/nacos-cluster.conf
    depends_on:
      - mysql
    networks:
      - vue3-network
    restart: unless-stopped

  nacos8853:
    image: nacos/nacos-server:2.1.0
    container_name: nacos-server
    ports:
      - "8853:8853"
    environment:
      MODE: cluster
      NACOS_SERVER_IP: 192.168.10.66
      NACOS_APPLICATION_PORT: 8853
      NACOS_SERVERS: "192.168.10.66:8841 192.168.10.66:8836 192.168.10.66:8853"
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
    volumes:
      - ./nacos-cluster.conf:/home/nacos/conf/nacos-cluster.conf
    depends_on:
      - mysql
    networks:
      - vue3-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - vue3-network


  nginx:
    image: nginx:latest
    container_name: nginx-balance
    ports:
      - "8848:8848"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nacos8841
      - nacos8836
      - nacos8853
    networks:
      - vue3-network

  nacosorderapi:
    image: zhangqstudy/nacosorderapi:latest
    container_name: nacosorderapi
    ports:
      - "8912:8912"
    networks:
      - vue3-network
    depends_on:
      - mysql
      - redis
      - kafka
    environment:
      - SERVER_PORT=8912
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/vue3db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
