version: '3.8'

volumes:
  mysql_data:

networks:
  vue3-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vue3db
      MYSQL_ROOT_HOST: '%' # 允许远程连接
    ports:
      - "3306:3306"
    networks:
      - vue3-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped #自动重启


  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes" #允许匿名登录dock
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - vue3-network

  kafka:
    image: apache/kafka:4.1.1
    # image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - vue3-network
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS=true #自动创建主题
    restart: unless-stopped

  # 第一个Nacos节点
  nacos8814:
    image: nacos/nacos-server:latest
    container_name: nacos-server8814
    ports:
      - "8814:8848"      # 主机端口8814映射到容器标准端口8848
      - "8824:8824"      # 控制台端口
    environment:
      - MODE=cluster
      - NACOS_SERVER_IP=192.168.1.18
      - NACOS_APPLICATION_PORT=8848      # 容器内仍使用标准端口
      - NACOS_CONSOLE_PORT=8824
      - NACOS_SERVERS=192.168.1.18:8814 192.168.1.18:8836 192.168.1.18:8853
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=vue3db
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=nacosidentitykey
      - NACOS_AUTH_IDENTITY_VALUE=nacosidentityvalue
      - EMBEDDED_STORAGE=embedded
    volumes:
      - ./nacos-cluster.conf:/home/conf/cluster.conf
    depends_on:
      - mysql
    networks:
      - vue3-network
    restart: unless-stopped

  # 第二个Nacos节点
  nacos8836:
    image: nacos/nacos-server:latest
    container_name: nacos-server8836
    ports:
      - "8836:8848"      # 主机端口8836映射到容器标准端口8848
      - "8846:8846"      # 控制台端口
    environment:
      - MODE=cluster
      - NACOS_SERVER_IP=192.168.1.18
      - NACOS_APPLICATION_PORT=8848      # 容器内仍使用标准端口
      - NACOS_CONSOLE_PORT=8846
      - NACOS_SERVERS=192.168.1.18:8814 192.168.1.18:8836 192.168.1.18:8853
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=vue3db
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=nacosidentitykey
      - NACOS_AUTH_IDENTITY_VALUE=nacosidentityvalue
      - EMBEDDED_STORAGE=embedded
    volumes:
      - ./nacos-cluster.conf:/home/conf/cluster.conf
    depends_on:
      - mysql
    networks:
      - vue3-network
    restart: unless-stopped

  # 第三个Nacos节点
  nacos8853:
    image: nacos/nacos-server:latest
    container_name: nacos-server8853
    ports:
      - "8853:8848"      # 主机端口8853映射到容器标准端口8848
      - "8863:8863"      # 控制台端口
    environment:
      - MODE=cluster
      - NACOS_SERVER_IP=192.168.1.18
      - NACOS_APPLICATION_PORT=8848      # 容器内仍使用标准端口
      - NACOS_CONSOLE_PORT=8863
      - NACOS_SERVERS=192.168.1.18:8814 192.168.1.18:8836 192.168.1.18:8853
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=vue3db
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=nacosidentitykey
      - NACOS_AUTH_IDENTITY_VALUE=nacosidentityvalue
      - EMBEDDED_STORAGE=embedded
    volumes:
      - ./nacos-cluster.conf:/home/conf/cluster.conf
    depends_on:
      - mysql
    networks:
      - vue3-network
    restart: unless-stopped

  # Nginx 负载均衡器
  nginx:
    image: nginx:latest
    container_name: nginx-balance
    ports:
      - "8848:8848"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nacos8814
      - nacos8836
      - nacos8853
    networks:
      - vue3-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - vue3-network