server:
  port: 8912

spring:
  application:
    name: nacos-order-api

  profiles:
    active: dev

  redis:
    database: 0 #Redis数据库索引，默认为0
    host: 192.168.10.34
    port: 6379
    password: redis
    jedis: #Jedis连接池配置
      pool:
        max-active: 10 #连接池最大活跃连接数，控制并发连接上限
        max-wait: 1000 #获取连接的最大等待时间(毫秒)，超时将抛出异常
        max-idle: 8 #连接池最大空闲连接数，保持的空闲连接上限
        min-idle: 5 #连接池最小空闲连接数，保持的空闲连接下限
    timeout: 1000 #redis操作超时时间(毫秒)，包括连接和读写超时


  datasource:
    url: jdbc:mysql://192.168.10.34:3306/vue3db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMulti
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #5版本之后替换为com.mysql.cj.jdbc.Driver

  #mybatis:
  #  mapper-locations: classpath:mapper/*.xml
  #  type-aliases-package: com.cloud.model

  #logging:
  #  level:
  #    com.cloud.dao: debug
  #    org.apache.ibatis: debug

  kafka:
    bootstrap-servers: 192.168.10.34:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #如果是对象，则要.JsonSerializer
      # 值的序列化方式
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer #修改为正确的序列化器
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
      transaction-id-prefix: tx- # 事务ID前缀，必须唯一
      enable-idempotence: true #幂等性，自动开启事务
      # 自定义分区器配置
      properties:
        partitioner.class: com.cloud.config.CustomerPartition
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false #是否自动提交offset
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 500 #单次拉取消息最大条数
      properties:
        spring.json.trusted.packages: "*" # kafka反序列化对象时，需要指定
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: MANUAL #消息确认模式：manual-手动确认，auto-自动确认
      missing-topics-fatal: false # consumer listener topics 不存在时，启动项目就会报错
      batch-listener: false #批量消费配置
      consumer:
        max-poll-records: 500  #每次拉取的记录数


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-create_table: true #自动建表
    #map-underscore-to-camel-case: true #驼峰命名  user_name -> userName